### ISSUE TITLE
Create Milestones and Zenhub board

### ISSUE THREAD

**Issue by yowill** [18F/dos-ops-center#1]
As a team member I want to have all the milestones, labels, and zenhub board set up so that I can start filling out the project backlog, tasks, and assigning sprints.

AC: 
- [x] Create and import Milestones
- [x] Set up the Zenhub board and swim lanes
- [x] Set up labels

**Comment by yowill** [comment]
It's here! Finished!
