### ISSUE TITLE
Testing search behavior and accuracy of proposed meta data structure

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#176]
As an 18F researcher, I would like to test the search behavior of CMS officers and Watch officers to observe and confirm search behavior (i.e. how they find what they need) so that we can see if the proposed meta data structure works or not (provided by @MeghanLuecke ) and/or if other elements need to be added to the data.

AC
- [ ] Request from @beebouttw export of subject lines
- [ ] Add subject line data to Airtable in preparation for testing
- [ ] Confirm typical search scenarios with @MeghanLuecke and @beebouttw 
- [ ] Do the tests
- [ ] Share updated "super set" of meta data with Meghan and Tyler
- [ ] Update the search-related user needs captured in the KMS repo with the results of the meta data test

**Comment by durland18F** [comment]
With reference to your comment on #136 Kara, yes these are the same thing.
