### ISSUE TITLE
Prototype and test co-editing in Drupal/Wordpress

### ISSUE THREAD

**Issue by matt-dobson** [18F/dos-ops-center#231]
# Co-editing in Drupal/Wordpress

### Tools
**Wordpress/Drupal**
* EtherPad
* TogetherJS
 

### Tasks
~~- [ ] [Set up TogetherJS in Wordpress (Cloud.gov?)](https://github.com/18F/dos-ops-center/issues/234)~~
- [x] [Write research protocol for co-editing testing](https://github.com/18F/dos-ops-center/issues/243)
- [x] [Scenario Refinement](https://github.com/18F/dos-ops-center/issues/246)
- [x] [Gather materials to test scenarios](https://github.com/18F/dos-ops-center/issues/245)
- [x] [Plan and Schedule user research session(s)](https://github.com/18F/dos-ops-center/issues/244)
- [x] [recruit research participants](https://github.com/18F/dos-ops-center/issues/248)
- [x] [Gather materials for test scenarios](https://github.com/18F/dos-ops-center/issues/245)
- [x] [Usability research session(s) for co-editing solutions](https://github.com/18F/dos-ops-center/issues/241)
- [x] [Analysis and Synthesis](https://github.com/18F/dos-ops-center/issues/242)
- [x] [Document and Report](https://github.com/18F/dos-ops-center/issues/242)

Future research:
- [ ] [Set up Etherpad in Drupal and/or Participad in Wordpress (understand differences)](https://github.com/18F/dos-ops-center/issues/239)

Support
@tadhg-ohiggins 
@stvnrlly 
@beebouttw 
@karareinsel 
@durland18F

**Comment by matt-dobson** [comment]
This is HUGE - we may want to consider converting to an epic and having smaller stories associated.
