### ISSUE TITLE
Dashboards - Generative Research 

### ISSUE THREAD

**Issue by matt-dobson** [18F/dos-ops-center#232]
# Generative user research to gain a better understanding of the user groups, needs, and context for each purpose and potential software products described as dashboards. 

**To uncover the user needs and unpack assumptions and interpretations of the definition of dashboard we can begin learning through low-fidelity prototypes, generative research, and co-creation exercises. As we get a clearer picture of each user’s needs we can more effectively define the scope of these problems and begin identifying and validating technical solutions.**

### Tasks
- [ ] Interview session with appropriate person from Ops to unpack and better understand CDI wireframes and E&I kick-off sketches
- [ ] Use dashboard interview synthesis to create generative research activities/low-fidelity prototypes
- [ ] Plan research sessions
- [ ] Execute research sessions
- [ ] Analysis and Synthesis
- [ ] Document and Report

**Comment by matt-dobson** [comment]
This is very large and may need to be converted into an Epic and/or smaller stories.
