### ISSUE TITLE
Outline content strategy timeline/roadmap

### ISSUE THREAD

**Issue by SwansonCL** [18F/dos-ops-center#266]
Develop a written outline of draft objectives and dates for remaining content strategy work.

AC:
- [ ] Review existing outcomes, progress, and future plans
- [ ] Seek input from Ops team on logical prioritization of tasks/goals
- [ ] Draft plan
- [ ] Get feedback from both 18F and Ops team members
- [ ] Revise as needed

**Comment by SwansonCL** [comment]
[https://app.zenhub.com/files/154224183/e065379e-853a-4573-876c-8e90f35d3a22/download](https://app.zenhub.com/files/154224183/e065379e-853a-4573-876c-8e90f35d3a22/download)
